org.gradle.jvmargs=-Xmx2G

mod_version=3.0.2
maven_group=com.dmsh
archives_base_name=ElytraStaffHelper

# ?????: ??????????? ? ????? ?????? Gradle ?????? Loom
loom_version=1.15-SNAPSHOT

minecraft_version=1.21.8
loader_version=0.18.4

# ???? ????? ???????? ?? fabric api ? ???????? ??????, ???????? ??????
fabric_api_version=0.136.1+1.21.8

# ?????: mappings ??? ???? ?????? (???? 1.21.8 ???, ???????? ????? 1.21.4)
yarn_mappings=1.21.8+build.1

modmenu_version=11.0.0
